diff --git Makefile Makefile
index 6fb6976..c7b9ffa 100644
--- Makefile
+++ Makefile
@@ -184,7 +184,7 @@ LIB_LDLIBS         = $(LIB_LDLIBS_STATIC) $(LIB_LDLIBS_SHARED)
 BIN_CPPFLAGS       = -include $(BUILD_DEFS) $(CPPFLAGS)
 BIN_CFLAGS         = -I$(SRCS_DIR) -fPIE -flto $(CFLAGS)
 BIN_LDFLAGS        = -L. -pie $(LDFLAGS) -Wl,-rpath='$$ORIGIN/../$$LIB'
-BIN_LDLIBS         = -l:$(LIB_SHARED) -ldl -lcap $(LDLIBS)
+BIN_LDLIBS         = -l:$(LIB_STATIC) -ldl -l:libcap.a -l:libseccomp.a $(LDLIBS)
 
 $(word 1,$(LIB_RPC_SRCS)): RPCGENFLAGS=-h
 $(word 2,$(LIB_RPC_SRCS)): RPCGENFLAGS=-c
