---
kind: pipeline
name: default
type: kubernetes

steps:
  - name: setup-ci
    image: autonomy/build-container:latest
    pull: always
    commands:
      - git fetch --tags
      - install-ci-key
      - setup-ci
    environment:
      SSH_KEY:
        from_secret: ssh_key
      DOCKER_CLI_EXPERIMENTAL: enabled
    volumes:
      - name: outer-docker-socket
        path: /var/outer-run
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: buildx
        path: /root/.docker/buildx

  - name: e2e-talos
    image: autonomy/build-container:latest
    pull: always
    environment:
      AZURE_STORAGE_ACCOUNT:
        from_secret: 'az_storage_account'
      AZURE_STORAGE_USER:
        from_secret: 'az_storage_user'
      AZURE_STORAGE_PASS:
        from_secret: 'az_storage_pass'
      AZURE_TENANT:
        from_secret: 'az_tenant'
    commands:
      - az login --service-principal -u "$${AZURE_STORAGE_USER}" -p "$${AZURE_STORAGE_PASS}" --tenant "$${AZURE_TENANT}"
      - make all extensions-metadata PUSH=true PLATFORM=linux/amd64
      - az storage blob upload --overwrite -f _out/extensions-metadata -n extensions-metadata -c "$${BUCKET_PATH}"
    when:
      event:
        - promote
      target:
        - e2e-talos
    volumes:
      - name: outer-docker-socket
        path: /var/outer-run
      - name: docker-socket
        path: /var/run
      - name: ssh
        path: /root/.ssh
      - name: buildx
        path: /root/.docker/buildx
    depends_on:
      - setup-ci

services:
- name: docker
  image: docker:20.10-dind
  entrypoint:
  - dockerd
  commands:
  - --dns=8.8.8.8
  - --dns=8.8.4.4
  - --mtu=1500
  - --log-level=error
  privileged: true
  volumes:
  - name: docker-socket
    path: /var/run
  - name: outer-docker-socket
    path: /var/outer-run
  - name: buildx
    path: /root/.docker/buildx
  - name: ssh
    path: /root/.ssh

volumes:
  - name: outer-docker-socket
    host:
      path: /var/ci-docker
  - name: docker-socket
    temp:
      medium: memory
  - name: buildx
    temp:
      medium: memory
  - name: ssh
    temp:
      medium: memory

trigger:
  branch:
    exclude:
    - renovate/*
    - dependabot/*

---
kind: pipeline
type: kubernetes
name: notify

clone:
  disable: true

steps:
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: proj-talos-maintainers
    when:
      status:
        - success
        - failure

trigger:
  branch:
    exclude:
    - renovate/*
    - dependabot/*
  status:
  - success
  - failure

depends_on:
  - default
