# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.13.2"

pre_release = false

preface = """\
See [Talos Linux documentation](https://docs.siderolabs.com/talos/v1.13/build-and-extend-talos/custom-images-and-development/system-extensions) for information on using system extensions.
"""

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
Linux Firmware: 20260519
ctr: 2.2.4
Intel u-code: 20260512
NVIDIA LTS: 580.159.04
ZFS: 2.4.2
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"
