# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.13.5"

pre_release = false

preface = """\
See [Talos Linux documentation](https://docs.siderolabs.com/talos/v1.13/build-and-extend-talos/custom-images-and-development/system-extensions) for information on using system extensions.
"""

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
cloudflared: 2026.6.1
gvisor: 20260622.0
kata-containers: 3.32.0
spin: 0.25.1
netbird: 0.73.2
linux-firmware: 20260622
tailscale: 1.98.5
soci-snapshotter: v0.14.1
wasmedge: 0.6.1
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"
