---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-iam-authenticator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-iam-authenticator
rules:
  - apiGroups:
      - iamauthenticator.k8s.aws
    resources:
      - iamidentitymappings
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - iamauthenticator.k8s.aws
    resources:
      - iamidentitymappings/status
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - aws-auth
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-iam-authenticator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-iam-authenticator
subjects:
  - kind: ServiceAccount
    name: aws-iam-authenticator
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: aws-iam-authenticator
  labels:
    k8s-app: aws-iam-authenticator
spec:
  selector:
    matchLabels:
      k8s-app: aws-iam-authenticator
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: aws-iam-authenticator
    spec:
      serviceAccountName: aws-iam-authenticator
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
        - key: CriticalAddonsOnly
          operator: Exists
      priorityClassName: system-cluster-critical
      containers:
        - name: aws-iam-authenticator
          image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon/aws-iam-authenticator:v0.7.10
          args:
            - server
            # IMPORTANT: Point to the pre-generated files from the extension
            - --config=/usr/local/lib/aws-iam-authenticator/config.yaml
            - --state-dir=/usr/local/lib/aws-iam-authenticator
            - --generate-kubeconfig=/usr/local/lib/aws-iam-authenticator/kubeconfig.yaml
            # IMPORTANT: Use pre-generated kubeconfig from the extension init process
            - --kubeconfig-pregenerated=true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: 20Mi
              cpu: 10m
            limits:
              memory: 20Mi
              cpu: 100m
          volumeMounts:
            - name: state
              mountPath: /usr/local/lib/aws-iam-authenticator/
      volumes:
        - name: state
          hostPath:
            path: /usr/local/lib/aws-iam-authenticator/
            type: Directory
